title: "St. Ives Tabletop"
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: "BoardGames"
        values:
            layout: boardgames
    -
        scope:
            path: "_posts"
        values:
            layout: post
NextSessionDate: 2019-10-09
SessionStart: "19:30"
SessionEnd: "23:00"
