title: "St. Ives Tabletop"
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: "BoardGames"
        values:
            layout: boardgames
sessionstart: "7:30pm"
