title: "St. Ives Tabletop"
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: "BoardGames"
        values:
            layout: boardgames
    -
        scope:
            path: "_posts"
        values:
            layout: post
